import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import './globals.css';
import { ConfigProvider } from 'antd';
import zhCN from 'antd/locale/zh_CN';
import 'dayjs/locale/zh-cn';
import { DayjsReg } from './components/DayjsReg';

export const metadata: Metadata = {
  title: 'OCI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <DayjsReg />
          <AntdRegistry>
            <ConfigProvider locale={zhCN} componentSize="small">
              {children}
            </ConfigProvider>
          </AntdRegistry>
        </main>
        {/*<Toaster />*/}
      </body>
    </html>
  );
}
