import type { Metadata } from 'next';
import Link from 'next/link';
import { Boxes, CarFront, HandCoins } from 'lucide-react';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { createServerSupabase } from '@/lib/supabase/server';
import { getUserProfileSnapshot } from '@/lib/user-profile';
import { Button } from '@/components/ui/button';
import UserNav from './components/user-nav';

export const metadata: Metadata = {
  title: 'OCI',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createServerSupabase();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  const profile = getUserProfileSnapshot(user);

  return (
    <html lang="en">
      <body>
        <main className="min-h-screen">
          {user ? (
            <header className="border-b bg-background">
              <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-2.5 sm:px-6">
                <nav className="flex items-center gap-1">
                  <Button asChild variant="ghost">
                    <Link href="/">
                      <Boxes className="size-4" />
                      首页
                    </Link>
                  </Button>
                  <Button asChild variant="ghost">
                    <Link href="/car">
                      <CarFront className="size-4" />
                      车辆
                    </Link>
                  </Button>
                  <Button asChild variant="ghost">
                    <Link href="/funds">
                      <HandCoins className="size-4" />
                      账单
                    </Link>
                  </Button>
                </nav>
                <UserNav profile={profile} />
              </div>
            </header>
          ) : null}
          <div className="mx-auto w-full max-w-7xl px-4 sm:px-6">{children}</div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
